/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogViewerUI.java
 *
  */
package com.UI;

import com.sun.org.apache.xml.internal.security.exceptions.Base64DecodingException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tkmagq7
 */
public class LogViewerUI extends javax.swing.JFrame {

    /** Creates new form LogViewerUI */
    public LogViewerUI() throws Base64DecodingException, Exception {
        initComponents();
        init();
        setTitle("Log Analyser Suite");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void init() throws Base64DecodingException, Exception {
      //  Sterling_InventoryMismatch fi = new Sterling_InventoryMismatch();
      //  this.jTabbedPane1.add("Inventory Mismatch", fi);
        try {
            LogAnalysis sim = new LogAnalysis();
            this.jTabbedPane1.add("Load and split Logs", sim);
        } catch (Exception e) {
            e.printStackTrace();
        }
        LogViewer con = new LogViewer();
        this.jTabbedPane1.add("Custom Log", con);
        NmonAnalysis nm=new NmonAnalysis();
        this.jTabbedPane1.add("Nmon Log", nm);
        RMS_UI rms=new RMS_UI();
      //  this.jTabbedPane1.add("RMS UI", rms);
        Batch_UI bat=new Batch_UI();
     //   this.jTabbedPane1.add("Batch UI", bat);
        Testdata_Esbfile esb=new Testdata_Esbfile();
     // this.jTabbedPane1.add("EsbdataGeneration", esb);
   //     SISFile D = new SISFile();
  //      this.jTabbedPane1.add("SIS File Transfer", D);
   //     OIC_SmokeTest s = new OIC_SmokeTest();
    //     this.jTabbedPane1.add("OIC Smoke Test", s);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {


                    new LogViewerUI().setVisible(true);
                } catch (Base64DecodingException ex) {
                    Logger.getLogger(LogViewerUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(LogViewerUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
